theme: jekyll-theme-midnight
title: Welcome to my blog!
description: I am a gradute student at University of South Florida. My blog is about self-supervised learning, neural architecture design and quantum computing. They are all different topics but as a Ph.D. student, these are very interesting topics.
